(()=>{
const X_BACKUP='uranai-ledger-last-backup-v1';
function xToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function xNorm(s){return String(s||'').normalize('NFKC').toLowerCase().replace(/[\s　。、！？!?.,・「」『』（）()［\][\]{}【】<>＜＞:：;；'"’”“`]/g,'')}
function xDupes(q){const n=xNorm(q);if(!n)return[];return logs.filter(x=>xNorm(x.q)===n)}
function xBackupText(){const s=localStorage.getItem(X_BACKUP);return s?`最終バックアップ記録：${new Date(s).toLocaleString()}`:'最終バックアップ記録：まだありません'}
function xRefreshBackup(){let el=document.getElementById('xLastBackup');if(!el){const host=document.getElementById('backupStatus');if(!host)return;el=document.createElement('div');el.id='xLastBackup';el.className='status';host.after(el)}el.textContent=xBackupText()}
function xRefreshOverdue(){const n=logs.filter(x=>x.check&&(x.grade||'未判定')==='未判定'&&x.check<xToday()).length;let el=document.getElementById('xOverdue');if(!el){el=document.createElement('section');el.id='xOverdue';el.className='panel';const main=document.querySelector('main');main.insertBefore(el,main.firstChild)}el.style.display=n?'block':'none';el.innerHTML=n?`<div class="title">期限切れ未判定</div><div style="font-weight:700;margin-top:6px">${n}件あります</div><button type="button" style="width:100%;margin-top:10px" onclick="location.href='search-all.html'">確認する</button>`:''}
function xSetupQuestionCheck(){const q=document.getElementById('q'),cast=document.getElementById('cast');if(!q||!cast)return;let info=document.getElementById('xDupeInfo');if(!info){info=document.createElement('div');info.id='xDupeInfo';info.className='status';q.after(info)}const refresh=()=>{const v=q.value.trim(),m=xDupes(v);info.textContent=v&&m.length?`同文・軽い表記ゆれ一致：${m.length}件（通算 #${m.map(x=>x.seq).join(', #')}）`:''};q.addEventListener('input',refresh);cast.addEventListener('click',ev=>{const m=xDupes(q.value.trim());if(m.length&&!confirm(`似た質問が${m.length}件あります。それでも占う？`)){ev.preventDefault();ev.stopImmediatePropagation()}},true)}
function xRecoverCreatedAt(){let changed=false;for(const item of logs){if(item.createdAt)continue;const m=String(item.id||'').match(/^L(\d{13})$/);if(!m)continue;const ms=Number(m[1]),d=new Date(ms);if(!Number.isFinite(ms)||Number.isNaN(d.getTime()))continue;const date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(item.date&&item.date!==date)continue;item.createdAt=d.toISOString();changed=true}if(changed)saveLocal()}
function xTimeText(item){if(!item.createdAt)return'';const d=new Date(item.createdAt);if(Number.isNaN(d.getTime()))return'';return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function xEnhanceCards(){xRecoverCreatedAt();document.querySelectorAll('#cards .card').forEach(card=>{if(card.dataset.xEnhanced)return;const num=card.querySelector('.numline'),n=num?.textContent||'',m=n.match(/通算\s*#(\d+)/),seq=m?Number(m[1]):null,item=logs.find(x=>Number(x.seq)===seq);if(!item)return;card.dataset.xEnhanced='1';const t=xTimeText(item);if(t&&num&&!num.textContent.includes(t))num.textContent+=` ／ ${t}`;card.style.position='relative';card.style.paddingRight='52px';const mark=document.createElement('button');mark.type='button';mark.textContent=item.important?'★':'☆';mark.setAttribute('aria-label',item.important?'重要を解除':'重要にする');mark.title=item.important?'重要を解除':'重要にする';mark.style.cssText='position:absolute;top:10px;right:10px;width:auto;border:0;background:transparent;font-size:24px;padding:4px 6px;line-height:1';mark.onclick=()=>{item.important=!item.important;saveLocal();render()};card.append(mark)})}
function xNthMonday(y,m,n){const first=new Date(y,m-1,1),offset=(8-first.getDay())%7;return 1+offset+(n-1)*7}
function xVernal(y){return Math.floor(20.8431+0.242194*(y-1980)-Math.floor((y-1980)/4))}
function xAutumnal(y){return Math.floor(23.2488+0.242194*(y-1980)-Math.floor((y-1980)/4))}
function xBaseHolidays(y){const s=new Set(),add=(m,d)=>s.add(`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`);add(1,1);add(1,xNthMonday(y,1,2));add(2,11);if(y>=2020)add(2,23);add(3,xVernal(y));add(4,29);add(5,3);add(5,4);add(5,5);add(7,xNthMonday(y,7,3));add(8,11);add(9,xNthMonday(y,9,3));add(9,xAutumnal(y));add(10,xNthMonday(y,10,2));add(11,3);add(11,23);return s}
function xHolidaySet(y){const s=xBaseHolidays(y);for(const k of [...s]){const [yy,mm,dd]=k.split('-').map(Number),d=new Date(yy,mm-1,dd);if(d.getDay()===0){let t=new Date(d);do{t.setDate(t.getDate()+1)}while(s.has(`${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,'0')}-${String(t.getDate()).padStart(2,'0')}`));s.add(`${t.getFullYear()}-${String(t.getMonth()+1).padStart(2,'0')}-${String(t.getDate()).padStart(2,'0')}`)}}for(let m=1;m<=12;m++){const days=new Date(y,m,0).getDate();for(let d=2;d<days;d++){const k=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`,p=`${y}-${String(m).padStart(2,'0')}-${String(d-1).padStart(2,'0')}`,n=`${y}-${String(m).padStart(2,'0')}-${String(d+1).padStart(2,'0')}`;if(!s.has(k)&&s.has(p)&&s.has(n))s.add(k)}}return s}
function xPaintCalendar(){const week=document.querySelector('.week');if(week&&week.children[0])week.children[0].style.color='#d00';const holidays=xHolidaySet(viewY);document.querySelectorAll('#calendar .day').forEach(btn=>{const d=Number(btn.querySelector('b')?.textContent||0);if(!d)return;const k=`${viewY}-${String(viewM).padStart(2,'0')}-${String(d).padStart(2,'0')}`,sun=new Date(viewY,viewM-1,d).getDay()===0;btn.style.color=(sun||holidays.has(k))?'#d00':''})}
const obs=new MutationObserver(()=>{xEnhanceCards();xPaintCalendar()});const cards=document.getElementById('cards');if(cards)obs.observe(cards,{childList:true,subtree:true});const cal=document.getElementById('calendar');if(cal)obs.observe(cal,{childList:true,subtree:true});
document.getElementById('backup')?.addEventListener('click',()=>{localStorage.setItem(X_BACKUP,new Date().toISOString());setTimeout(xRefreshBackup,0)});
xSetupQuestionCheck();xRecoverCreatedAt();xRefreshBackup();xRefreshOverdue();xEnhanceCards();xPaintCalendar();
})();